### ISSUE TITLE
Calling 'has' in list context can return an empty list

### ISSUE THREAD

**Issue by kentfredric** [dagolden/recommended#1]
Found this when exploring `use if eval {  }` related issues.

The given code sample causes very unusual behaviour. Fortunately, no code that is written this way will do anything other than behave weirdly, which will naturally deter people from shipping code that way.

``` perl

use recommended { "Foo" => 5.000 };
use if recommended->has("FooTypoHere"), "SomeModuleName", { @args };
```

Here, the `has` statement is always reduced to the empty list, causing the code to say:

``` perl
use if "SomeModuleName", { @args };
```

Where "SomeModuleName" is now the condition (always true ) and  `{}`  is now the module name to load.

``` perl
Can't locate HASH(0x181e140).pm in @INC (you may need to install the HASH(0x181e140) module) ... at /home/kent/perl5/perlbrew/perls/5.21.8-c/lib/5.21.9/if.pm line 13
```

This behaviour differs from the case where "Foo" is matching in `$SPEC` but is simply not installed, where it gives a solid undef.

``` perl
use recommended { "Foo" => 5.00 };
use if recommended->has('Foo'), "Test::Requires" => { Bar => 1 }; #good
```

**Comment by dagolden** [comment]
It's sufficient to change `return unless $spec` to `return 0 unless $spec`, right?

I think the other returns are always defined.

**Comment by kentfredric** [comment]
Yah. Any scalar value does the trick as long as its false. 

`has` is semantically true/false anyway.

``` perl
return undef unless $spec;
```

Should also be suitable I imagine.

**Comment by kentfredric** [comment]
``` perl
  return $spec->[1] = $ok ? 1 : 0;
```

Ah. right. 0 is better then. Thanks =).
